import uniqid from 'uniqid';
export const data = [
    {
        id:uniqid(),
        category:"New",
        img:"https://images.eksmo.ru/images/book_harm_01-min.jpg",
        author:"Muslim Bolot",
        date:"22.08.22",
    },
    {
        id:uniqid(),
        category:"New",
        img:"https://images.eksmo.ru/images/book_harm_01-min.jpg",
        author:"Muslim Bolot",
        date:"22.08.22",
    },
    {
        id:uniqid(),
        category:"New",
        img:"https://images.eksmo.ru/images/book_harm_01-min.jpg",
        author:"Muslim Bolot",
        date:"22.08.22",
    },
    {
        id:uniqid(),
        category:"New",
        img:"https://images.eksmo.ru/images/book_harm_01-min.jpg",
        author:"Muslim Bolot",
        date:"22.08.22",
    },
    {
        id:uniqid(),
        category:"New",
        img:"https://images.eksmo.ru/images/book_harm_01-min.jpg",
        author:"Muslim Bolot",
        date:"22.08.22",
    },
    {
        id:uniqid(),
        category:"New",
        img:"https://images.eksmo.ru/images/book_harm_01-min.jpg",
        author:"Muslim Bolot",
        date:"22.08.22",
    },
    {
        id:uniqid(),
        category:"New",
        img:"https://images.eksmo.ru/images/book_harm_01-min.jpg",
        author:"Muslim Bolot",
        date:"22.08.22",
    },
    {
        id:uniqid(),
        category:"New",
        img:"https://gilber.one/wp-content/uploads/12-pravil-zhizni.-protivojadie-ot-haosa.jpg",
        author:"Muslim Bolot",
        date:"22.08.22",
    },
    {
        id:uniqid(),
        category:"New",
        img:"https://images.eksmo.ru/images/book_harm_01-min.jpg",
        author:"Muslim Bolot",
        date:"22.08.22",
    },
    {
        id:uniqid(),
        category:"New",
        img:"https://images.eksmo.ru/images/book_harm_01-min.jpg",
        author:"Muslim Bolot",
        date:"22.08.22",
    },
    {
        id:uniqid(),
        category:"New",
        img:"https://images.eksmo.ru/images/book_harm_01-min.jpg",
        author:"Muslim Bolot",
        date:"22.08.22",
    },
    {
        id:uniqid(),
        category:"New",
        img:"https://images.eksmo.ru/images/book_harm_01-min.jpg",
        author:"Muslim Bolot",
        date:"22.08.22",
    },
    {
        id:uniqid(),
        category:"New",
        img:"https://images.eksmo.ru/images/book_harm_01-min.jpg",
        author:"Muslim Bolot",
        date:"22.08.22",
    },
    {
        id:uniqid(),
        category:"New",
        img:"https://images.eksmo.ru/images/book_harm_01-min.jpg",
        author:"Muslim Bolot",
        date:"22.08.22",
    },
    {
        id:uniqid(),
        category:"New",
        img:"https://images.eksmo.ru/images/book_harm_01-min.jpg",
        author:"Muslim Bolot",
        date:"22.08.22",
    },
    {
        id:uniqid(),
        category:"New",
        img:"https://images.eksmo.ru/images/book_harm_01-min.jpg",
        author:"Muslim Bolot",
        date:"22.08.22",
    },
    {
        id:uniqid(),
        category:"New",
        img:"https://images.eksmo.ru/images/book_harm_01-min.jpg",
        author:"Muslim Bolot",
        date:"22.08.22",
    },
    {
        id:uniqid(),
        category:"New",
        img:"https://images.eksmo.ru/images/book_harm_01-min.jpg",
        author:"Muslim Bolot",
        date:"22.08.22",
    },
]
export const courses = [
    {
        id:uniqid(),
        img:"https://www.premium-transmission.com/uploads/slider/grow1669181363.jpeg?6028",
        education:"Обучение",
    }, {
        id:uniqid(),
        img:"https://www.premium-transmission.com/uploads/slider/grow1669181363.jpeg?6028",
        education:"Обучение",
    }, {
        id:uniqid(),
        img:"https://www.premium-transmission.com/uploads/slider/grow1669181363.jpeg?6028",
        education:"Обучение",
    },

]